export const SIGNUP = "SIGNUP";
export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

//signin

export const SIGNIN = "SIGNIN";
export const SIGNIN_LOADING = "SIGNIN_LOADING";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";

// author name

export const AUTHORNAME = "AUTHORNAME";
export const AUTHORNAME_LOADING = "AUTHORNAME_LOADING";
export const AUTHORNAME_SUCCESS = "AUTHORNAME_SUCCESS";
export const AUTHORNAME_ERROR = "AUTHORNAME_ERROR";

// save blogpost
export const SAVEBLOGPOST = "SAVEBLOGPOST";
export const SAVEBLOGPOST_LOADING = "SAVEBLOGPOST_LOADING";
export const SAVEBLOGPOST_SUCCESS = "SAVEBLOGPOST_SUCCESS";
export const SAVEBLOGPOST_ERROR = "SAVEBLOGPOST_ERROR";

// get blogs

export const GETBLOGPOST = "GETBLOGPOST";
export const GETBLOGPOST_LOADING = "GETBLOGPOST_LOADING";
export const GETBLOGPOST_SUCCESS = "GETBLOGPOST_SUCCESS";
export const GETBLOGPOST_ERROR = "GETBLOGPOST_ERROR";